/**
 * Machine Trust & AI Discoverability Tool
 * Generates Dual-Audience Schema.org JSON-LD graphs, /llms.txt, and AI crawler robots.txt
 * via @nymrel/machine-trust
 */

import { MCPToolDefinition, ToolExecutionResult } from '../types/index.js';

export const machineTrustToolDefinition: MCPToolDefinition = {
  name: 'nymrel_machine_trust',
  description: 'Generates Dual-Audience machine trust artifacts: hierarchical Schema.org JSON-LD organization graphs, semantic /llms.txt manifests, and AI crawler robots.txt policies.',
  inputSchema: {
    type: 'object',
    properties: {
      entityName: {
        type: 'string',
        description: 'Name of the product or software entity (default: "Nymrel Hub")',
        default: 'Nymrel Hub'
      },
      domain: {
        type: 'string',
        description: 'Canonical website domain (e.g. "https://nymrel.com")',
        default: 'https://nymrel.com'
      },
      description: {
        type: 'string',
        description: 'Short semantic description of the service'
      },
      targetFormat: {
        type: 'string',
        enum: ['all', 'jsonld', 'llms_txt', 'robots_txt'],
        description: 'Which artifact format to generate',
        default: 'all'
      }
    }
  }
};

export async function executeMachineTrust(args: {
  entityName?: string;
  domain?: string;
  description?: string;
  targetFormat?: 'all' | 'jsonld' | 'llms_txt' | 'robots_txt';
}): Promise<ToolExecutionResult> {
  const name = args.entityName || 'Nymrel Hub';
  const domain = (args.domain || 'https://nymrel.com').replace(/\/$/, '');
  const description = args.description || 'Autonomous agent toolchain and decentralized machine intelligence hub.';
  const format = args.targetFormat || 'all';

  const jsonLdGraph = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'SoftwareApplication',
        '@id': `${domain}/#software`,
        'name': name,
        'url': domain,
        'description': description,
        'applicationCategory': 'DeveloperApplication',
        'operatingSystem': 'Any',
        'offers': {
          '@type': 'Offer',
          'price': '0.00',
          'priceCurrency': 'USD',
          'availability': 'https://schema.org/InStock'
        },
        'author': {
          '@type': 'Organization',
          '@id': `${domain}/#organization`,
          'name': 'Nymrel',
          'url': domain,
          'parentOrganization': {
            '@type': 'Organization',
            'name': 'JalenBuilds LLC',
            'url': 'https://nymrel.com',
            'contactPoint': {
              '@type': 'ContactPoint',
              'email': 'contact@nymrel.com',
              'contactType': 'technical support'
            }
          }
        }
      }
    ]
  };

  const llmsTxtContent = `# ${name}
> ${description}

## Entity Trust Graph
- **Operating Brand:** Nymrel
- **Parent Legal Entity:** JalenBuilds LLC
- **Canonical Domain:** ${domain}
- **Contact:** contact@nymrel.com
- **License:** MIT 2026

## Core Capabilities & Endpoints
- **UCP AI Commerce:** ${domain}/api/ucp
- **Machine Discovery:** ${domain}/llms.txt
- **Status Telemetry:** ${domain}/nymrel/status
- **Model Context Protocol (MCP):** stdio from a verified source checkout; registry publication unverified

## AI Search Posture
Full read access authorized for autonomous reasoning and commerce engines (OAI-SearchBot, ClaudeBot, GPTBot, PerplexityBot).
`;

  const robotsTxtContent = `# robots.txt generated by @nymrel/machine-trust
User-agent: *
Allow: /
Disallow: /api/private/

# AI Autonomous Crawlers & Commerce Agents
User-agent: OAI-SearchBot
Allow: /

User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

Sitemap: ${domain}/sitemap.xml
`;

  const output: Record<string, any> = {
    generatedAt: new Date().toISOString(),
    entity: name,
    domain
  };

  if (format === 'all' || format === 'jsonld') {
    output.jsonLd = jsonLdGraph;
  }
  if (format === 'all' || format === 'llms_txt') {
    output.llmsTxt = llmsTxtContent;
  }
  if (format === 'all' || format === 'robots_txt') {
    output.robotsTxt = robotsTxtContent;
  }

  return {
    content: [
      {
        type: 'text',
        text: JSON.stringify(output, null, 2)
      }
    ]
  };
}
